# Generated by Django 2.0.7 on 2018-07-15 22:23

from django.db import migrations, models
import django.db.models.deletion
import validators.month_year_validator
import validators.phone_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.TimeField()),
                ('reference_month', models.IntegerField(validators=[validators.month_year_validator.validate_month])),
                ('reference_year', models.IntegerField(validators=[validators.month_year_validator.validate_year])),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CallEndRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallStartRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.IntegerField(unique=True)),
                ('destination', models.CharField(max_length=11, validators=[validators.phone_validator.validate_phone])),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarrif_type', models.CharField(choices=[('standard', 'standard'), ('reduced', 'reduced')], max_length=8)),
                ('standing_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('call_charge', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(db_column='id', max_length=11, primary_key=True, serialize=False, unique=True, validators=[validators.phone_validator.validate_phone])),
            ],
        ),
        migrations.AddField(
            model_name='callstartrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Subscriber'),
        ),
        migrations.AddField(
            model_name='billrecord',
            name='call_start_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CallStartRecord'),
        ),
        migrations.AddField(
            model_name='billrecord',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Subscriber'),
        ),
    ]
