# Generated by Django 2.0.6 on 2018-07-01 15:27

from django.db import migrations, models
import validators.phone_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[validators.phone_validator.validate_phone])),
            ],
        ),
    ]
