# Generated by Django 2.0.7 on 2018-07-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billrecord',
            name='call_duration',
        ),
    ]
