# Generated by Django 2.0.7 on 2018-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_billrecord_call_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='call_duration',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
