# Generated by Django 2.0.6 on 2018-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_callstartrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEndRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='call_id',
            field=models.IntegerField(),
        ),
    ]
