# Generated by Django 2.0.6 on 2018-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180702_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callendrecord',
            name='call_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='call_id',
            field=models.IntegerField(unique=True),
        ),
    ]
