# Generated by Django 2.0.7 on 2018-07-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180702_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarrif_type', models.CharField(choices=[('standard', 'standard'), ('reduced', 'reduced')], max_length=8)),
                ('standing_charge', models.DecimalField(decimal_places=3, max_digits=5)),
                ('call_charge', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
