# Generated by Django 2.0.7 on 2018-07-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='call_charge',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='price',
            name='standing_charge',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
