# Generated by Django 2.0.7 on 2018-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180704_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default='jessica', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(default='paz', max_length=30),
            preserve_default=False,
        ),
    ]
