# Generated by Django 2.0.7 on 2018-07-05 14:53

from django.db import migrations, models
import django.db.models.deletion
import validators.month_year_validator


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180704_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_duration', models.TimeField()),
                ('reference_month', models.IntegerField(validators=[validators.month_year_validator.validate_month])),
                ('reference_year', models.IntegerField(validators=[validators.month_year_validator.validate_year])),
                ('call_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('call_start_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.CallStartRecord')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Subscriber')),
            ],
        ),
    ]
