# Generated by Django 2.0.7 on 2018-07-07 21:07

from django.db import migrations, models
import django.db.models.deletion
import validators.phone_validator


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_billrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.AlterField(
            model_name='billrecord',
            name='call_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='destination',
            field=models.CharField(max_length=11, validators=[validators.phone_validator.validate_phone]),
        ),
        migrations.AlterField(
            model_name='callstartrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Subscriber'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(db_column='id', editable=False, max_length=11, primary_key=True, serialize=False, unique=True, validators=[validators.phone_validator.validate_phone]),
        ),
    ]
