# Generated by Django 2.0.7 on 2018-07-07 21:22

from django.db import migrations, models
import validators.phone_validator


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180707_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='phone_number',
            field=models.CharField(db_column='id', max_length=11, primary_key=True, serialize=False, unique=True, validators=[validators.phone_validator.validate_phone]),
        ),
    ]
